config/routes.rb
RentingGuild::Application.routes.draw do

  resources :renters
  
  get "get_your_guide", to: 'renters#new'
  
  get "download", to: 'renters#download'
  
  root to: 'renters#new'
end

app/models/renter.rb
class Renter < ActiveRecord::Base
  include ActiveModel::Validations
  include GoingPostal
 
  attr_accessible :email, :postcode
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => 'Please provide a valid email address.'

  class PostcodeValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
      record.errors.add attribute, (options[:message] || "Please provide a valid UK postcode.") unless
      GoingPostal.postcode?(value, "GB")
    end
  end

  validates :postcode, :postcode => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
  include NearRentify

  def index
    @renters = Renter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @renters }
    end
  end

  def show
    @renter = Renter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @renter }
    end
  end

  def new
    @renter = Renter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @renter }
    end
  end

  def edit
    @renter = Renter.find(params[:id])
  end

  def create
    @renter = Renter.new(params[:renter])
      
    respond_to do |format|
      if @renter.save
      
		  if(is_within_5_miles(@renter[:postcode]))
			  @within_5_miles = true
			  #coordinates = get_coordinates(@renter[:postcode])
			  #@link_to_map = "<img src=\"#{create_link(coordinates)}\" class=\"img-circle\">"
		   end
		   
		   DownloadNotifier.downloaded(@renter).deliver	   
		   format.js 
		   format.html { redirect_to @renter, notice: 'Renter was successfully created.' }
		   format.json { render json: @renter, status: :created, location: @renter }
      else
	  	   format.js {@render} 
        format.html { render action: "new" }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /renters/1
  # PUT /renters/1.json
  def update
    @renter = Renter.find(params[:id])

    respond_to do |format|
      if @renter.update_attributes(params[:renter])
        format.html { redirect_to @renter, notice: 'Renter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renters/1
  # DELETE /renters/1.json
  def destroy
    @renter = Renter.find(params[:id])
    @renter.destroy

    respond_to do |format|
      format.html { redirect_to renters_url }
      format.json { head :no_content }
    end
  end
  
  def download
  	file_path = Rails.root + "public/Ultimate_Renting_Guide.pdf"
  	send_file file_path, filename: "Ultimate_Renting_Guide.pdf", disposition: "attachment"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/views/download_notifier/downloaded.html.erb
<h3>Download Comfirmation</h3>
<p>
Thank you for sign up with us and enjoy your reading.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentingGuild</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults, "rails.validations" %>
  <%= csrf_meta_tags %>

</head>
<body>
          <div id="carousel" class="carousel slide">
			  		
			  		<div class="carousel-caption rentify_logo">
			  			<%= image_tag "rentify.png"%>
			  		</div>
			  		
                   <div class="carousel-caption">
					   <h3>The Ultimate Renting Guide</h3>
					   <p>  Ut tincidunt tortor. Donec nonummy</p>
					   <p>  Enim in laciniavelit tellus scelerisque augue, 
                          ac posuere libero urna eget neque. Cras ipsum. Vestibulum pretium, lectus nec venenatis volutpat, 
                          purus lectus ultrices risus, a condimentum risus mi et quam. Pellentesque auctor fringilla neque. 
						  Duis eu massa ut lorem iaculis vestibulum. Maecenas 
					   </p>
					   <p>  Maecenas sed diam eget risus varius blandit sit amet non magna. Donec id elit non mi porta gravida 
					   	at eget.</p>                                                                    
                       <a href="#myModal" role="button" class="btn" data-toggle="modal"><div class="sign_up">Sign Up</div></a>      
					</div>
         
					<div class="carousel-inner">                
                        <div class="active item">
                                <%= image_tag "cozy_room_1.jpg"  %>
                        </div>                        
                        <div class="item">
                                <%= image_tag "cozy_room_2.jpg"  %>
                        </div>                        
					</div>                
                <a class="carousel-control left" href="#carousel" data-slide="prev">&lsaquo;</a>
                <a class="carousel-control right" href="#carousel" data-slide="next">&rsaquo;</a> 
        </div>        
        
        <%= yield %>
        
        
        
</body>
</html>

app/views/renters/_form.html.erb
<%= form_for @renter, :remote => true, :validate => true do |f| %>

  <%= f.text_field :postcode, :id=>"inputIcon", :placeholder=>"Postcode"%>
  <%= f.text_field :email, :id=>"inputIcon", :placeholder=>"Email"%>
  <%= f.submit "Download Your Guide", :class => 'btn' %>

<% end %>

app/views/renters/create.js.erb
<% if @renter.errors.any? %>
  $(".alert").alert();
  $('#failed').html("<%=j render "form" %>");
<% elsif @within_5_miles %>
  download_guide();
  $('#failed').hide(); 
  $('#map_to_rentify').attr('src', 'http://maps.googleapis.com/maps/api/staticmap?zoom=15&size=300x300&maptype=roadmap&markers=color:orange%7Clabel:R%7C51.526417,-0.078261&sensor=false');
  $('#success_within_5_miles').fadeIn('slow');
<% else %>
  download_guide();
  $('#failed').hide();
  $('#success').fadeIn('slow');
<% end %>

function download_guide(){
	var url='http://0.0.0.0:3000/download';
    var _iframe_dl = $('<iframe />').attr('src', url).hide().appendTo('body'); 
}

app/views/renters/edit.html.erb
<%- model_class = Renter -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/renters/index.html.erb
<%- model_class = Renter -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:postcode) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @renters.each do |renter| %>
      <tr>
        <td><%= link_to renter.id, renter_path(renter) %></td>
        <td><%= renter.postcode %></td>
        <td><%= renter.email %></td>
        <td><%=l renter.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_renter_path(renter), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      renter_path(renter),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_renter_path,
            :class => 'btn btn-primary' %>

app/views/renters/new.html.erb
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 
	<div id="failed" class="modal-body">
    	<%= render 'form' %>
	</div>

	<div id="success" class="modal-body success">
		<%= image_tag "success_kid.jpg", :class => "img-circle"%>
		<p class="lead">You just successfully downloaded the Ultimate Renting Guide.</p>
	</div>

	<div id="success_within_5_miles" class="modal-body success_within_5_miles">
		<img id="map_to_rentify" src="" class="img-circle">
		<p class="lead">The Guide is on its way and you are very close to our base.</p>
	</div>


</div>

app/views/renters/show.html.erb
<%- model_class = Renter -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:postcode) %>:</strong></dt>
  <dd><%= @renter.postcode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @renter.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              renters_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_renter_path(@renter), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              renter_path(@renter),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>